version: "3.3"
services:
  mariadb:
    image: mariadb:11.0.2
    ports:
      - 3306:3306
    volumes:
      - C:\Users\Han\Mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  api:
    image: allmnet/my:bot_api
    ports:
      - 80:8080
    environment:
      DB_PASSWORD: password
      LOG_LVL: prod
      PYTHONUNBUFFERED: 1
    depends_on:
      - mariadb
    command:
      "sh -c /opt/bbot/start.sh"
